baseURL: https://jas0nhuang.netlify.app
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Jason's Website
params:
  address: Regent's Park, London, United Kingdom
  author: Jason Huang
  baidu_analytics_id: ''
  baidu_site_verification: ''
  contact:
    enable: no
    form_action: '#'
  cookies:
    enable: no
    expire_days: 2
  copyright: Copyright &copy; 2021 Jason Huang
  description: This is meta description
  email: jas0nhg176@gmail.com
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.525970'
    map_longitude: '-0.162950'
    map_marker: images/marker.png
  phone: +44 07563 161073
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - URL: 'https://www.linkedin.com/in/zhicheng-jason-huang/'
      icon: ti-linkedin
    - URL: 'https://www.instagram.com/jas0nhuang01/'
      icon: ti-instagram
  theme_color: '#41228e'
menu:
  main:
    - URL: about/
      name: About
      weight: 1
    - URL: blog/
      name: Blog
      weight: 2
    - URL: contact/
      name: Social
      weight: 3
